apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election-demo
  template:
    metadata:
      labels:
        app: leader-election-demo
    spec:
      serviceAccountName: leader-election-sa
      containers:
      - name: leader-election-demo
        image: leader-election-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
